package com.chennan.mysite.cnyy.mybatis.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table award
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Award implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_id
     *
     * @mbg.generated
     */
    private Integer awardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_name
     *
     * @mbg.generated
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table award
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_id
     *
     * @return the value of award.award_id
     *
     * @mbg.generated
     */
    public Integer getAwardId() {
        return awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_id
     *
     * @param awardId the value for award.award_id
     *
     * @mbg.generated
     */
    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_name
     *
     * @return the value of award.award_name
     *
     * @mbg.generated
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_name
     *
     * @param awardName the value for award.award_name
     *
     * @mbg.generated
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName;
    }
}