package com.chennan.mysite.cnyy.mybatis.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table skill
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Skill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.skill_id
     *
     * @mbg.generated
     */
    private Integer skillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.skill_name
     *
     * @mbg.generated
     */
    private String skillName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.skill_score
     *
     * @mbg.generated
     */
    private Integer skillScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.skill_id
     *
     * @return the value of skill.skill_id
     *
     * @mbg.generated
     */
    public Integer getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.skill_id
     *
     * @param skillId the value for skill.skill_id
     *
     * @mbg.generated
     */
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.skill_name
     *
     * @return the value of skill.skill_name
     *
     * @mbg.generated
     */
    public String getSkillName() {
        return skillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.skill_name
     *
     * @param skillName the value for skill.skill_name
     *
     * @mbg.generated
     */
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.skill_score
     *
     * @return the value of skill.skill_score
     *
     * @mbg.generated
     */
    public Integer getSkillScore() {
        return skillScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.skill_score
     *
     * @param skillScore the value for skill.skill_score
     *
     * @mbg.generated
     */
    public void setSkillScore(Integer skillScore) {
        this.skillScore = skillScore;
    }
}